INSERT INTO COR (cod_cor, nome_cor) VALUES (199, 'AZUL');
INSERT INTO COR (cod_cor, nome_cor) VALUES (200, 'AMARELO');
INSERT INTO COR (cod_cor, nome_cor) VALUES (201, 'BRANCO');
INSERT INTO COR (cod_cor, nome_cor) VALUES (202, 'ROSA');
INSERT INTO COR (cod_cor, nome_cor) VALUES (216, 'BRANCO - ADAPTADA (BRAILE E LEDOR)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (195, 'AZUL');
INSERT INTO COR (cod_cor, nome_cor) VALUES (196, 'AMARELO');
INSERT INTO COR (cod_cor, nome_cor) VALUES (197, 'BRANCO');
INSERT INTO COR (cod_cor, nome_cor) VALUES (198, 'ROSA');
INSERT INTO COR (cod_cor, nome_cor) VALUES (215, 'BRANCO - ADAPTADA (BRAILE E LEDOR)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (203, 'AMARELO');
INSERT INTO COR (cod_cor, nome_cor) VALUES (204, 'CINZA');
INSERT INTO COR (cod_cor, nome_cor) VALUES (205, 'AZUL');
INSERT INTO COR (cod_cor, nome_cor) VALUES (206, 'ROSA');
INSERT INTO COR (cod_cor, nome_cor) VALUES (213, 'CINZA (REAPLICAÇÃO)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (217, 'CINZA - ADAPTADA (BRAILE E LEDOR)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (207, 'AMARELO');
INSERT INTO COR (cod_cor, nome_cor) VALUES (208, 'CINZA');
INSERT INTO COR (cod_cor, nome_cor) VALUES (209, 'AZUL');
INSERT INTO COR (cod_cor, nome_cor) VALUES (210, 'ROSA');
INSERT INTO COR (cod_cor, nome_cor) VALUES (214, 'CINZA (REAPLICAÇÃO)');
INSERT INTO COR (cod_cor, nome_cor) VALUES (218, 'CINZA - ADAPTADA (BRAILE E LEDOR)');
