INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (01,'Quantas pessoas moram com você?');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (02,'Até quando seu pai estudou?');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (03,'Até quando sua mãe estudou?');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (04,'Qual é a renda mensal de sua família? (Some a sua renda com a dos seus familiares)');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (05,'A residência de sua família é');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (06,'A residência de sua família está localizada em');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (07,'Você exerce ou já exerceu atividade remunerada?');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (08,'Você tem em sua casa? TV em cores');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (09,'Você tem em sua casa? Videocassete e/ou DVD');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (10,'Você tem em sua casa? Rádio');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (11,'Você tem em sua casa? Microcomputador');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (12,'Você tem em sua casa? Automóvel');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (13,'Você tem em sua casa? Máquina de lavar roupa');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (14,'Você tem em sua casa? Geladeira');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (15,'Você tem em sua casa? Freezer (aparelho independente ou parte da geladeira duplex)');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (16,'Você tem em sua casa? Telefone fixo');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (17,'Você tem em sua casa? Telefone celular');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (18,'Você tem em sua casa? Acesso à Internet');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (19,'Você tem em sua casa? TV por assinatura');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (20,'Você tem em sua casa? Aspirador de pó');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (21,'Você tem em sua casa? Empregada mensalista'); 
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (22,'Você tem em sua casa? Banheiro');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (23,'Indique o que levou você a participar do ENEM: Testar meus conhecimentos');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (24,'Indique os motivos que levaram você a participar do ENEM: Aumentar a possibilidade de conseguir um emprego');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (25,'Indique os motivos que levaram você a participar do ENEM: Progredir no meu emprego atual');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (26,'Indique o que levou você a participar do ENEM: Prosseguir os estudos no Ensino Superior');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (27,'Indique os motivos que levaram você a participar do ENEM: Ingressar na Educação Superior Privada');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (28,'Indique o que levou você a participar do ENEM: Conseguir uma bolsa de estudos (ProUni, outras)');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (29,'Indique os motivos que levaram você a participar do ENEM: Participar do Programa de Financiamento Estudantil - FIES');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (30,'Quantos anos você levou para concluir o Ensino Fundamental?');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (31,'Você deixou de estudar durante o Ensino Fundamental?');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (32,'Em que tipo de escola você cursou o Ensino Fundamental?');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (33,'Quantos anos você levou para concluir o Ensino Médio?');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (34,'Você deixou de estudar durante o Ensino Médio?');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (35,'Em que tipo de escola você cursou o Ensino Médio?');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (36,'Caso você ingresse no Ensino Superior privado pretende recorrer aos auxílios abaixo para custeio das mensalidades? Pró-Uni (Programa Universidade para Todos)');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (37,'Caso você ingresse no Ensino Superior privado pretende recorrer aos auxílios abaixo para custeio das mensalidades? Bolsa de estudos da própria Instituição de Ensino Superior');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (38,'Caso você ingresse no Ensino Superior privado pretende recorrer aos auxílios abaixo para custeio das mensalidades? Bolsa de estudos da empresa onde trabalho');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (39,'Caso você ingresse no Ensino Superior privado pretende recorrer aos auxílios abaixo para custeio das mensalidades? Auxílio do Programa de Financiamento Estudantil - FIES');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (40,'Com que idade você começou a exercer uma atividade remunerada?');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (41,'Quantas horas semanais você trabalha ou trabalhou aproximadamente?');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (42,'Indique a importância de cada um dos motivos abaixo na sua decisão de trabalhar: Ajudar meus pais nas despesas com a residência');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (43,'Indique a importância de cada um dos motivos abaixo na sua decisão de trabalhar: Sustentar minha família (esposo/a, filhos/as etc.)');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (44,'Indique a importância de cada um dos motivos abaixo na sua decisão de trabalhar: Ser independente/ganhar meu próprio dinheiro');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (45,'Indique a importância de cada um dos motivos abaixo na sua decisão de trabalhar: Adquirir experiência');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (46,'Indique a importância de cada um dos motivos abaixo na sua decisão de trabalhar: Custear/pagar meus estudos');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (47,'Indique os cursos que você frequenta ou frequentou: Curso profissionalizante');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (48,'Indique os cursos que você frequenta ou frequentou: Curso preparatório para vestibular');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (49,'Indique os cursos que você frequenta ou frequentou: Curso superior');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (50,'Indique os cursos que você frequenta ou frequentou: Curso de língua estrangeira');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (51,'Indique os cursos que você frequenta ou frequentou: Curso de computação ou informática');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (52,'Indique os cursos que você frequenta ou frequentou: Curso preparatório para concursos públicos');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (53,'Indique os cursos que você frequenta ou frequentou: Outro curso');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (54,'Você cursa ou já cursou a Educação de Jovens e Adultos – EJA?');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (55,'Como é ou era o principal curso de EJA que você frequenta ou frequentou?');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (56,'Indique o que levou você a deixar de cursar a EJA (Se você não deixou de cursar a EJA, vá para a questão...): Trabalhava, não tinha tempo de estudar');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (57,'Indique o que levou você a deixar de cursar a EJA (Se você não deixou de cursar a EJA, vá para a questão...): Estudava no curso da empresa e foi interrompido');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (58,'Indique o que levou você a deixar de cursar a EJA (Se você não deixou de cursar a EJA, vá para a questão...): Ocorreram problemas de saúde ou acidentes comigo ou familiares');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (59,'Indique o que levou você a deixar de cursar a EJA (Se você não deixou de cursar a EJA, vá para a questão...): Mudei de bairro, cidade ou município');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (60,'Indique o que levou você a deixar de cursar a EJA (Se você não deixou de cursar a EJA, vá para a questão...): Por motivos pessoais, casamento, filhos etc.');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (61,'Indique o que levou você a deixar de cursar a EJA (Se você não deixou de cursar a EJA, vá para a questão...): Faltava-me interesse, desisti');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (62,'Indique o que levou você a deixar de cursar a EJA (Se você não deixou de cursar a EJA, vá para a questão...): Senti-me discriminado(a)');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (63,'Você já frequentou o ensino regular?');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (64,'Indique o que levou você a deixar de cursar o ensino regular: Falta de vaga em escola pública');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (65,'Indique o que levou você a deixar de cursar o ensino regular: Ausência de escola perto de casa');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (66,'Indique o que levou você a deixar de cursar o ensino regular: Falta de interesse em estudar');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (67,'Indique o que levou você a deixar de cursar o ensino regular: Trabalho, falta de tempo para estudar');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (68,'Indique o que levou você a deixar de cursar o ensino regular: Motivos pessoais, casamento/filhos etc.');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (69,'Indique o que levou você a deixar de cursar o ensino regular: Falta de apoio familiar.');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (70,'Indique o que levou você a deixar de cursar o ensino regular: Problemas de saúde ou acidente comigo ou familiares');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (71,'Indique o que levou você a deixar de cursar o ensino regular: Discriminação/Preconceitos (sexo, raça, idade, classe etc.)');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (72,'Quantos anos você tinha quando deixou de frequentar o ensino regular?');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (73,'Indique o que levou você a deixar de cursar a EJA (Se você não deixou de cursar a EJA, vá para a questão...): Temi/Sofri violência');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (74,'Indique o que levou você a deixar de cursar o ensino regular: Dificuldades após reprovação');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (75,'Indique o que levou você a deixar de cursar o ensino regular: Falta de condições adequadas na escola');
INSERT INTO questao_socioeconomico (sequencial_questionario_socio, questao) VALUES (76,'Indique o que levou você a deixar de cursar o ensino regular: Medo de sofrer violência');